CRITICAL - 2021-01-12 00:03:10 --> Class 'App\Models\tank_auth\users' not found
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:04:41 --> Undefined variable: ci
#0 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Users.php(44): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 44, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(109): App\Models\Users->__construct(NULL)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(40): CodeIgniter\Database\ModelFactory::createClass('App\\Models\\User...', NULL)
#3 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(774): CodeIgniter\Database\ModelFactory::get('App\\Models\\tank...', true, NULL)
#4 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(27): model('App\\Models\\tank...')
#5 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#8 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-01-12 00:06:18 --> Undefined property: App\Libraries\Tank_auth::$config
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 28, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 00:06:59 --> Undefined property: Config\tank_auth::$session
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(166): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 166, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(576): App\Libraries\Tank_auth->is_logged_in()
#2 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(31): App\Libraries\Tank_auth->autologin()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-12 00:08:27 --> Undefined property: Config\tank_auth::$load
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(577): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 577, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(31): App\Libraries\Tank_auth->autologin()
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 00:10:28 --> Undefined property: Config\tank_auth::$load
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(579): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 579, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(31): App\Libraries\Tank_auth->autologin()
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 00:10:58 --> Undefined property: Config\tank_auth::$config
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(580): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 580, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(31): App\Libraries\Tank_auth->autologin()
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): App\Libraries\Tank_auth->__construct()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 00:12:25 --> syntax error, unexpected ';'
#0 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('G:\\xampp\\htdocs...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Libraries\\T...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Libraries\\T...')
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): spl_autoload_call('App\\Libraries\\T...')
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-12 00:13:56 --> syntax error, unexpected ';'
#0 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('G:\\xampp\\htdocs...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Libraries\\T...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Libraries\\T...')
#3 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(41): spl_autoload_call('App\\Libraries\\T...')
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-01-12 00:15:14 --> Undefined variable: tank_auth_lib
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(71): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 71, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:36:14 --> Undefined variable: tank_auth_lib
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(71): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 71, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:36:31 --> Undefined property: App\Controllers\Auth::$input
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(89): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 89, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:37:47 --> Undefined property: App\Controllers\Auth::$input
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(89): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 89, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:39:56 --> Undefined variable: tank_auth
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(95): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 95, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 00:40:25 --> Undefined property: Config\tank_auth::$config
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(624): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 624, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(96): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 00:41:58 --> Undefined property: Config\tank_auth::$load
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(625): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 625, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(96): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 01:00:36 --> Cannot access parent:: when current class scope has no parent
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(76): App\Models\tank_auth\Login_attempts->__construct()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(40): CodeIgniter\Database\ModelFactory::createClass('App\\Models\\tank...', NULL)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(774): CodeIgniter\Database\ModelFactory::get('App\\Models\\tank...', true, NULL)
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(630): model('App\\Models\\tank...')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 01:01:43 --> Call to undefined function App\Models\tank_auth\get_instance()
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(76): App\Models\tank_auth\Login_attempts->__construct()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\ModelFactory.php(40): CodeIgniter\Database\ModelFactory::createClass('App\\Models\\tank...', NULL)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(774): CodeIgniter\Database\ModelFactory::get('App\\Models\\tank...', true, NULL)
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(630): model('App\\Models\\tank...')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 01:01:58 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 03:07:12 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 03:58:22 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 04:44:05 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 04:45:35 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 05:00:05 --> Undefined variable: db
#0 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 58, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 05:01:18 --> Undefined variable: builder
#0 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(60): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 60, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 05:02:15 --> Undefined variable: builder
#0 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(61): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'G:\\xampp\\htdocs...', 61, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 05:02:49 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 05:02:49 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 05:07:46 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 05:07:46 --> Uncaught ErrorException: var_dump(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'var_dump(): Pro...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): var_dump(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 09:56:00 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 09:56:00 --> Uncaught ErrorException: var_dump(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'var_dump(): Pro...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): var_dump(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 09:56:06 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 09:56:06 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 09:57:35 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 09:57:35 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 09:57:37 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 09:57:37 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 10:00:35 --> Table 'pime_somali.ctbl_users_login_attempts' doesn't exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT 1\nFROM `...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#6 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(102): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#8 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-01-12 10:04:00 --> Undefined property: App\Controllers\Auth::$form_validation
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(110): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 110, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 10:10:12 --> Invalid file: auth/login_form.php
#0 G:\xampp\htdocs\UBS\pime_somali\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/login_form...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(1119): CodeIgniter\View\View->render('auth/login_form', Array, true)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(111): view('auth/login_form', Array)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 10:12:50 --> Invalid file: auth/login_form.php
#0 G:\xampp\htdocs\UBS\pime_somali\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/login_form...')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Common.php(1119): CodeIgniter\View\View->render('auth/login_form', Array, true)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(111): view('auth/login_form', Array)
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-01-12 10:14:10 --> Undefined property: App\Controllers\Auth::$load
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(138): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 138, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 10:14:10 --> Undefined property: App\Controllers\Auth::$load
#0 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(138): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'G:\\xampp\\htdocs...', 138, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-01-12 10:16:38 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:43 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:44 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:44 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:55 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:57 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:16:58 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:18:05 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:18:08 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:18:38 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:18:59 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:19:01 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:19:02 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:19:02 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:19:49 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:20:21 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:20:22 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:20:29 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 10:20:29 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:13:31 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:13:43 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:13:54 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 21:13:54 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 21:14:30 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:14:39 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(21): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:49 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:51 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:52 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:52 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:52 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:17:53 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:30:31 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 21:30:34 -->  route cannot be found while reverse-routing.
#0 G:\xampp\htdocs\UBS\pime_somali\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Login.php(63): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Login->index()
#3 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#4 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 G:\xampp\htdocs\UBS\pime_somali\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-01-12 23:17:47 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:17:48 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 23:19:43 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515183.893, 0.0291, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:19:51 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515191.0575, 0.0305, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:19:59 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515199.6444, 0.0277, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:20:01 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515201.4653, 0.0234, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:20:01 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515201.7755, 0.0256, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:20:06 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515206.4697, 0.0245, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:20:21 --> Class login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515221.3286, 0.0243, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:05 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515325.7305, 0.0358, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:07 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515327.9406, 0.0337, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:08 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515328.1627, 0.0238, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:14 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515334.6805, 0.0262, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:15 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515335.2596, 0.0231, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:15 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515335.469, 0.0237, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:15 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515335.6715, 0.0237, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:15 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515335.9097, 0.0247, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:16 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515336.4504, 0.0234, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:22:16 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515336.6579, 0.0235, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:28:45 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515725.7613, 0.2134, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:29:10 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515750.4377, 0.0311, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:29:20 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515759.7811, 0.3448, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:29:22 --> Class Login does not exist
#0 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\Routes.php(107): ReflectionMethod->__construct('Login', '_remap')
#1 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar\Collectors\BaseCollector.php(307): CodeIgniter\Debug\Toolbar\Collectors\Routes->display()
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(128): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Toolbar.php(356): CodeIgniter\Debug\Toolbar->run(1610515762.3273, 0.0234, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#4 G:\xampp\htdocs\UBS\pime_somali\system\Filters\DebugToolbar.php(78): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse))
#5 G:\xampp\htdocs\UBS\pime_somali\system\Filters\Filters.php(199): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\RedirectResponse), NULL)
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(422): CodeIgniter\Filters\Filters->run('', 'after')
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:30:44 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:30:44 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 23:30:59 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:30:59 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-01-12 23:42:19 --> Unable to connect to the database.
#0 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 G:\xampp\htdocs\UBS\pime_somali\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 G:\xampp\htdocs\UBS\pime_somali\app\Models\tank_auth\Login_attempts.php(65): CodeIgniter\Database\BaseBuilder->get()
#3 G:\xampp\htdocs\UBS\pime_somali\app\Libraries\Tank_auth.php(632): App\Models\tank_auth\Login_attempts->get_attempts_num('127.0.0.1', '')
#4 G:\xampp\htdocs\UBS\pime_somali\app\Controllers\Auth.php(101): App\Libraries\Tank_auth->is_max_login_attempts_exceeded('')
#5 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(918): App\Controllers\Auth->login()
#6 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 G:\xampp\htdocs\UBS\pime_somali\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp\htdocs\UBS\pime_somali\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-01-12 23:42:20 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'G:\\xampp\\htdocs...', 100, Array)
#1 G:\xampp\htdocs\UBS\pime_somali\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Auth), true)
#2 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(308): include('G:\\xampp\\htdocs...')
#3 G:\xampp\htdocs\UBS\pime_somali\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
